# Generated by Django 5.0.6 on 2024-05-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_remove_videos_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='desktop_file',
            field=models.FileField(blank=True, null=True, upload_to='post_videos'),
        ),
        migrations.AddField(
            model_name='videos',
            name='mobile_file',
            field=models.FileField(blank=True, null=True, upload_to='post_videos'),
        ),
        migrations.AddField(
            model_name='videos',
            name='tablet_file',
            field=models.FileField(blank=True, null=True, upload_to='post_videos'),
        ),
    ]
